name: greatghoul/angular-file-upload
author:
  name: greatghoul
  email: greatghoul@gmail.com
  url: 'http://www.g2w.me'
copyright: 2015 greatghoul
description: Angular File Upload is a module for the AngularJS framework
